version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "sh -c 'rm -f /rails/tmp/pids/server.pid && bundle exec rails s -p 3333 -b 0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3333:3333"
    environment:
      RAILS_ENV: development
      TZ: Asia/Seoul       # 컨테이너 내부 타임존 환경 변수
    networks:
      - asst
    restart: always
    mem_limit: 2g  # 메모리 제한 설정

    labels:
      # 1) Traefik을 통해 라우팅을 허용
      - "traefik.enable=true"

      # 2) HTTP -> HTTPS 리다이렉트 설정
      - "traefik.http.routers.rails-web.rule=Host(`www.asst.kr`)"    # HTTP 라우터
      - "traefik.http.routers.rails-web.entrypoints=http"
      - "traefik.http.routers.rails-web.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # 3) HTTPS 설정
      - "traefik.http.routers.rails-web-secure.rule=Host(`www.asst.kr`)"  # HTTPS 라우터
      - "traefik.http.routers.rails-web-secure.entrypoints=https"
      - "traefik.http.routers.rails-web-secure.tls.certresolver=myresolver"
      - "traefik.http.services.rails-web.loadbalancer.server.port=3333"   # 내부 포트

      # /sidekiq 경로 추가 설정
      # - "traefik.http.middlewares.sidekiq-stripprefix.stripprefix.prefixes=/sidekiq"
      # - "traefik.http.routers.sidekiq.rule=Host(`www.asst.kr`) && PathPrefix(`/sidekiq`)"
      # - "traefik.http.routers.sidekiq.middlewares=sidekiq-stripprefix"
      # - "traefik.http.routers.sidekiq.entrypoints=https"
      # - "traefik.http.routers.sidekiq.tls.certresolver=myresolver"

      # # 여기서 포트를 3333으로 변경!!
      # - "traefik.http.services.sidekiq.loadbalancer.server.port=3333"

networks:
  asst:
    external: true


