:concurrency: 20
:queues:
  - default
  - mailers

# :scheduler:
#   :schedule:
#     fetch_upbit_price_job:
#       every: ["10s"]  # 매 1분마다 실행
#       class: "FetchUpbitPriceJob"
#       queue: default


# UpbitApiService.sell_10_percent_of_balance_if_profit_rate_between_10_and_15 직접 호출 하도록 수정
:scheduler:
  :schedule:
    bitcoin_account_profit_sell_tradin_job:
      every: ["10s"]
      class: "BitcoinAccountProfitSellTradingJob"
      queue: default

# :scheduler:
#   :schedule:
#     fetch_update_alpha_vantage_exchange_rates_job:
#       every: ["10s"]  # 매 10초마다 실행
#       class: "FetchUpdateAlphaVantageExchangeRatesJob"
#       queue: default